openapi: 3.0.0
info:
  title: User API
  description: API para la gestión de usuarios
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      tags:
        - Users
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error al traer los usuarios

  /users/{uid}:
    get:
      summary: Obtener usuario por ID
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: El usuario no existe
        '500':
          description: Error al traer el usuario

  /users/register:
    post:
      summary: Registrar un nuevo usuario
      tags:
        - Users
      requestBody:
        description: Datos del nuevo usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuario registrado correctamente
        '400':
          description: Datos faltantes o inválidos
        '409':
          description: El mail ya está registrado
        '500':
          description: Error al registrar el usuario

  /users/login:
    post:
      summary: Iniciar sesión
      tags:
        - Users
      requestBody:
        description: Credenciales de usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: string
                description: Token JWT
        '400':
          description: Email y/o password incorrectas
        '500':
          description: Error al iniciar sesión

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        age:
          type: integer
        password:
          type: string
