openapi: 3.0.0
info:
  title: Product API
  description: API para la gestión de productos
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
            description: Número de página para la paginación
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            description: Cantidad de productos por página
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error al traer los productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      requestBody:
        description: Datos del nuevo producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Producto creado correctamente
        '400':
          description: Datos faltantes o inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al crear el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products/{id}:
    get:
      summary: Obtener producto por ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: El producto no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al traer el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Actualizar un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        description: Datos actualizados del producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Producto actualizado correctamente
        '400':
          description: Datos faltantes o inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: El producto no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al actualizar el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Eliminar un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto eliminado correctamente
        '404':
          description: El producto no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al eliminar el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        status:
          type: boolean
          default: true
        stock:
          type: number
        category:
          type: string
        owner:
          type: string
          default: 'admin'
        thumbnails:
          type: array
          items:
            type: string
      required:
        - title
        - description
        - code
        - price
        - stock
        - category

    NewProduct:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        status:
          type: boolean
          default: true
        stock:
          type: number
        category:
          type: string
        owner:
          type: string
          default: 'admin'
        thumbnails:
          type: array
          items:
            type: string
      required:
        - title
        - description
        - code
        - price
        - stock
        - category

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
