openapi: 3.0.0
info:
  title: Cart API
  description: API para la gestión de carritos de compra
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/carts/
    description: Servidor local

paths:
  /carts:
    get:
      summary: Obtener todos los carritos
      tags:
        - Carts
      responses:
        '200':
          description: Lista de carritos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        '500':
          description: Error al traer los carritos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Crear un nuevo carrito
      tags:
        - Carts
      requestBody:
        description: Datos del nuevo carrito
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCart'
      responses:
        '201':
          description: Carrito creado correctamente
        '400':
          description: Datos faltantes o inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al crear el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /carts/{id}:
    get:
      summary: Obtener carrito por ID
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        '200':
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: El carrito no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al traer el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Actualizar un carrito
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del carrito
      requestBody:
        description: Datos actualizados del carrito
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCart'
      responses:
        '200':
          description: Carrito actualizado correctamente
        '400':
          description: Datos faltantes o inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: El carrito no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al actualizar el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Eliminar un carrito
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        '200':
          description: Carrito eliminado correctamente
        '404':
          description: El carrito no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al eliminar el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: ID del producto
              quantity:
                type: number
                default: 1
      required:
        - products

    NewCart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: ID del producto
              quantity:
                type: number
                default: 1
      required:
        - products

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
